#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mpsrouter
  name: mpsrouter
spec:
  ports:
  - port: 8003
    name: mpsrouter
    protocol: TCP
    targetPort: 8003
  selector:
    app: mpsrouter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpsrouter
  namespace: default
spec:
  replicas: {{ .Values.mpsrouter.replicaCount }}
  selector:
    matchLabels:
      app: mpsrouter
  template:
    metadata:
      labels:
        app: mpsrouter
    spec:
      imagePullSecrets:
        - name: registrycredentials
      containers:
        - name: mpsrouter
          image:  {{ .Values.images.mpsrouter }}
          env:
            - name: "MPS_CONNECTION_STRING"
              value: "{{ .Values.mpsrouter.connectionString }}"
            - name: "MPS_ROUTER_PORT"
              value: "8003"
            - name: "MPS_SERVER_PORT"
              value: "3000"
          ports:
            - containerPort: 8003
              name: mpsrouter